In [120]:
import pandas as pd

df = pd.read_excel("C:/Users/anwar salman/OneDrive/Desktop/12/E-commerce project - Copy (4) - Copy.xlsx")
print(df.head())

   Row ID Order Priority  Discount  Unit Price  Shipping Cost  Customer ID  \
0   20847           High      0.01        2.84           0.93            3
1   20228  Not Specified      0.02      500.98          26.00            5
2   21776       Critical      0.06        9.48           7.29           11
3   24844            NaN      0.09       78.69          19.99           14
4   24846            NaN      0.08        3.28           2.31           14

       Customer Name       Ship Mode Customer Segment Product Category  ...  \
0      Bonnie Potter     Express Air        Corporate  Office Supplies  ...
1     Ronnie Proctor  Delivery Truck      Home Office        Furniture  ...
2      Marcus Dunlap     Regular Air      Home Office        Furniture  ...
3                NaN             NaN   Small Business        Furniture  ...
4  Gwendolyn F Tyson     Regular Air   Small Business  Office Supplies  ...

    Region State or Province         City  Postal Code Order Date  Ship Date  \
0     West        Washington    Anacortes      98221.0 2015-01-07 2015-01-08
1     West        California  San Gabriel      91776.0 2015-06-13 2015-06-15
2     East        New Jersey      Roselle       7203.0 2015-02-15 2015-02-17
3  Central               NaN          NaN      55372.0 2015-05-12 2015-05-14
4  Central         Minnesota   Prior Lake      55372.0 2015-05-12 2015-05-13

      Profit Quantity ordered new    Sales Order ID
0     4.5600                    4    13.01    88522
1  4390.3665                   12  6362.85    90193
2   -53.8096                   22   211.15    90192
3   803.4705                   16  1164.45    86838
4   -24.0300                    7    22.23    86838

[5 rows x 25 columns]

In [121]:
df.head()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221.0,2015-01-07,2015-01-08,4.5600,4,13.01,88522
1,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776.0,2015-06-13,2015-06-15,4390.3665,12,6362.85,90193
2,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203.0,2015-02-15,2015-02-17,-53.8096,22,211.15,90192
3,24844,NaN,0.09,78.69,19.99,14,NaN,NaN,Small Business,Furniture,...,Central,NaN,NaN,55372.0,2015-05-12,2015-05-14,803.4705,16,1164.45,86838
4,24846,NaN,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372.0,2015-05-12,2015-05-13,-24.0300,7,22.23,86838

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2330 entries, 0 to 2329
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                2330 non-null   int64
 1   Order Priority        2325 non-null   object
 2   Discount              2330 non-null   float64
 3   Unit Price            2330 non-null   float64
 4   Shipping Cost         2330 non-null   float64
 5   Customer ID           2330 non-null   int64
 6   Customer Name         2328 non-null   object
 7   Ship Mode             2324 non-null   object
 8   Customer Segment      2330 non-null   object
 9   Product Category      2330 non-null   object
 10  Product Sub-Category  2330 non-null   object
 11  Product Container     2330 non-null   object
 12  Product Name          2330 non-null   object
 13  Product Base Margin   2308 non-null   float64
 14  Country               2330 non-null   object
 15  Region                2330 non-null   object
 16  State or Province     2325 non-null   object
 17  City                  2324 non-null   object
 18  Postal Code           2322 non-null   float64
 19  Order Date            2330 non-null   datetime64[ns]
 20  Ship Date             2330 non-null   datetime64[ns]
 21  Profit                2330 non-null   float64
 22  Quantity ordered new  2330 non-null   int64
 23  Sales                 2330 non-null   float64
 24  Order ID              2330 non-null   int64
dtypes: datetime64[ns](2), float64(7), int64(4), object(12)
memory usage: 455.2+ KB

In [123]:
df.describe()

,Row ID,Discount,Unit Price,Shipping Cost,Customer ID,Product Base Margin,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
count,2330.000000,2330.000000,2330.000000,2330.000000,2330.000000,2308.000000,2322.000000,2330,2330,2330.000000,2330.000000,2330.000000,2330.000000
mean,20097.203004,0.049378,105.435498,12.786322,1950.562661,0.514259,51403.680448,2015-03-29 08:53:58.454935552,2015-03-31 06:46:02.575107328,125.998393,12.768670,961.045021,82943.789270
min,64.000000,0.000000,1.140000,0.490000,3.000000,0.350000,1001.000000,2015-01-01 00:00:00,2015-01-02 00:00:00,-16476.838000,1.000000,2.250000,359.000000
25%,19179.750000,0.020000,6.480000,3.140000,1008.250000,0.380000,29621.000000,2015-02-11 00:00:00,2015-02-13 00:00:00,-81.460000,5.000000,58.330000,86793.000000
50%,21261.000000,0.050000,20.990000,6.150000,2062.500000,0.520000,48308.500000,2015-03-29 00:00:00,2015-03-30 00:00:00,1.950400,9.000000,199.530000,88403.500000
75%,23452.000000,0.080000,99.990000,13.990000,3036.000000,0.590000,78586.000000,2015-05-15 00:00:00,2015-05-16 18:00:00,118.436775,16.000000,768.810000,89981.000000
max,26389.000000,0.210000,6783.020000,164.730000,3403.000000,0.850000,99362.000000,2015-06-30 00:00:00,2015-07-08 00:00:00,9228.225600,167.000000,45737.330000,91586.000000
std,5736.832558,0.031737,377.296350,17.093039,1076.687057,0.136981,29463.907768,NaN,NaN,1105.125629,13.366395,2442.385055,18322.205983

In [124]:
df.isnull()

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,True,False,False,False,False,True,True,False,False,...,False,True,True,False,False,False,False,False,False,False
4,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2325,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2326,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2327,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2328,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2329,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [125]:
df.isnull().sum()

Row ID                   0
Order Priority           5
Discount                 0
Unit Price               0
Shipping Cost            0
Customer ID              0
Customer Name            2
Ship Mode                6
Customer Segment         0
Product Category         0
Product Sub-Category     0
Product Container        0
Product Name             0
Product Base Margin     22
Country                  0
Region                   0
State or Province        5
City                     6
Postal Code              8
Order Date               0
Ship Date                0
Profit                   0
Quantity ordered new     0
Sales                    0
Order ID                 0
dtype: int64

In [126]:
df[df.isnull().any(axis=1)]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
3,24844,NaN,0.09,78.69,19.99,14,NaN,NaN,Small Business,Furniture,...,Central,NaN,NaN,55372.0,2015-05-12,2015-05-14,803.4705,16,1164.45,86838
4,24846,NaN,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372.0,2015-05-12,2015-05-13,-24.0300,7,22.23,86838
5,24847,Medium,0.05,3.28,4.20,14,Gwendolyn F Tyson,NaN,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372.0,2015-05-12,2015-05-13,-37.0300,4,13.99,86838
6,24848,Medium,0.05,3.58,1.63,14,NaN,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,NaN,2015-05-12,2015-05-13,-0.7100,4,14.26,86838
7,18181,NaN,0.00,4.42,4.99,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,East,New York,Smithtown,NaN,2015-04-08,2015-04-09,-59.8200,7,33.47,86837
8,20925,Medium,0.01,35.94,6.66,15,Timothy Reese,NaN,Small Business,Office Supplies,...,East,NaN,Smithtown,NaN,2015-05-28,2015-05-28,261.8757,10,379.53,86839
9,26267,NaN,0.04,2.98,1.58,16,Sarah Ramsey,NaN,Small Business,Office Supplies,...,East,NaN,Syracuse,13210.0,2015-02-12,2015-02-15,2.6300,6,18.80,86836
10,26268,High,0.05,115.99,2.50,16,Sarah Ramsey,NaN,Small Business,Technology,...,East,New York,NaN,13210.0,2015-02-12,2015-02-14,652.7331,10,945.99,86836
11,23890,High,0.05,26.48,6.93,18,Laurie Hanna,Regular Air,Small Business,Furniture,...,West,Montana,NaN,59601.0,2015-05-15,2015-05-16,314.4813,17,455.77,90031
12,24063,NaN,0.07,12.99,9.44,19,Jim Rodgers,NaN,Small Business,Technology,...,West,Montana,Missoula,NaN,2015-05-21,2015-05-23,-114.6399,18,231.79,90032
13,5890,High,0.05,26.48,6.93,21,Tony Wilkins Winters,Regular Air,Small Business,Furniture,...,East,New York,New York City,NaN,2015-05-15,2015-05-16,384.3800,70,1876.69,41793
14,6062,Not Specified,0.08,5.00,3.39,21,Tony Wilkins Winters,Regular Air,Small Business,Office Supplies,...,East,New York,NaN,10012.0,2015-05-21,2015-05-22,-17.4900,58,293.06,42949
16,20631,High,0.06,55.48,14.30,24,Edna Thomas,Regular Air,Corporate,Office Supplies,...,West,NaN,Laguna Niguel,NaN,2015-01-28,2015-01-29,-28.2968,1,67.49,87651
17,20632,High,0.02,1.68,1.57,24,Edna Thomas,Regular Air,Corporate,Office Supplies,...,West,NaN,Laguna Niguel,92677.0,2015-01-28,2015-01-30,-5.3072,1,2.25,87651
19,23509,High,0.08,34.99,7.73,32,Matthew Berman,Regular Air,Corporate,Office Supplies,...,West,Oregon,NaN,NaN,2015-02-22,2015-02-23,144.6900,13,424.68,89199
20,23612,High,0.01,17.98,8.51,32,Matthew Berman,Regular Air,Corporate,Technology,...,West,Oregon,NaN,NaN,2015-03-27,2015-03-28,-35.8788,2,40.17,89200
181,18261,Critical,0.06,276.20,24.49,335,Curtis O'Connell,Regular Air,Corporate,Furniture,...,West,Oregon,Medford,97504.0,2015-05-04,2015-05-05,2639.4708,14,3825.32,87277
271,18305,Critical,0.01,128.24,12.65,508,Cameron Owens,Regular Air,Corporate,Furniture,...,South,Kentucky,Covington,41011.0,2015-04-18,2015-04-21,140.1354,4,554.08,87357
483,24764,Critical,0.09,349.45,60.00,868,Sharon Ellis,Delivery Truck,Corporate,Furniture,...,Central,Minnesota,Shoreview,55126.0,2015-03-06,2015-03-07,-2946.0510,12,3918.98,91195
660,19185,High,0.09,349.45,60.00,1178,Sandy Hunt,Delivery Truck,Consumer,Furniture,...,South,Florida,Altamonte Springs,32701.0,2015-04-09,2015-04-10,-369.1100,7,2307.26,89787
700,20592,Medium,0.03,128.24,12.65,1237,Eva Simpson,Regular Air,Corporate,Furniture,...,Central,Texas,Carrollton,75007.0,2015-01-31,2015-02-02,790.4640,9,1145.60,86075
727,21848,Not Specified,0.08,128.24,12.65,1267,Rosemary Branch,Regular Air,Corporate,Furniture,...,South,Florida,Boca Raton,33433.0,2015-05-12,2015-05-13,-379.3440,3,366.44,89515
734,22125,Low,0.10,238.40,24.49,1281,Pauline Denton,Regular Air,Small Business,Furniture,...,Central,Indiana,Vincennes,47591.0,2015-01-24,2015-01-26,875.2844,8,1774.50,89112
736,4125,Low,0.10,238.40,24.49,1282,Dana Sharpe,Regular Air,Small Business,Furniture,...,East,Pennsylvania,Philadelphia,19134.0,2015-01-24,2015-01-26,460.6760,30,6654.39,29319
977,22593,High,0.09,349.45,60.00,1739,Edna Pierce,Delivery Truck,Corporate,Furniture,...,South,North Carolina,Goldsboro,27534.0,2015-05-03,2015-05-04,-90.7480,17,5835.41,85867
1228,19914,Not Specified,0.08,95.99,35.00,2211,Anita Hahn,Express Air,Home Office,Office Supplies,...,East,Maryland,Bowie,20715.0,2015-01-01,2015-01-03,-425.2084,2,193.88,88028
1507,19525,Critical,0.01,138.14,35.00,2660,Jeffrey Page,Regular Air,Small Business,Office Supplies,...,East,Maine,Gorham,4038.0,2015-02-24,2015-02-26,-321.5100,4,599.03,86486
1729,23188,High,0.06,276.20,24.49,3048,Tracy G Starr,Express Air,Corporate,Furniture,...,West,California,Berkeley,94704.0,2015-03-05,2015-03-07,1167.3800,10,2610.56,89789
1774,20795,Critical,0.08,349.45,60.00,3119,Jay Hubbard,Delivery Truck,Corporate,Furniture,...,South,Florida,Orlando,32839.0,2015-06-30,2015-07-02,513.0840,11,3772.19,86432
1860,18728,Not Specified,0.01,349.45,60.00,3257,Sharon Marcus,Delivery Truck,Consumer,Furniture,...,West,Washington,Longview,98632.0,2015-05-26,2015-05-27,3739.3929,15,5419.41,88825
1935,23182,Critical,0.09,276.20,24.49,3380,Eva Decker,Regular Air,Home Office,Furniture,...,South,Georgia,La Grange,30240.0,2015-04-20,2015-04-21,3193.2840,11,2941.42,88838
1943,19464,Not Specified,0.03,95.99,35.00,3388,Aaron Shaffer,Regular Air,Corporate,Office Supplies,...,West,California,Fairfield,94533.0,2015-05-11,2015-05-12,67.0120,9,894.64,90154
2045,18728,Not Specified,0.01,349.45,60.00,3257,Sharon Marcus,Delivery Truck,Consumer,Furniture,...,West,Washington,Longview,98632.0,2015-05-26,2015-05-27,3739.3929,15,5419.41,88825
2120,23182,Critical,0.09,276.20,24.49,3380,Eva Decker,Regular Air,Home Office,Furniture,...,South,Georgia,La Grange,30240.0,2015-04-20,2015-04-21,3193.2840,11,2941.42,88838
2128,19464,Not Specified,0.03,95.99,35.00,3388,Aaron Shaffer,Regular Air,Corporate,Office Supplies,...,West,California,Fairfield,94533.0,2015-05-11,2015-05-12,67.0120,9,894.64,90154
2230,18728,Not Specified,0.01,349.45,60.00,3257,Sharon Marcus,Delivery Truck,Consumer,Furniture,...,West,Washington,Longview,98632.0,2015-05-26,2015-05-27,3739.3929,15,5419.41,88825
2305,23182,Critical,0.09,276.20,24.49,3380,Eva Decker,Regular Air,Home Office,Furniture,...,South,Georgia,La Grange,30240.0,2015-04-20,2015-04-21,3193.2840,11,2941.42,88838
2313,19464,Not Specified,0.03,95.99,35.00,3388,Aaron Shaffer,Regular Air,Corporate,Office Supplies,...,West,California,Fairfield,94533.0,2015-05-11,2015-05-12,67.0120,9,894.64,90154

In [127]:
df.isnull().any(axis=1)

0       False
1       False
2       False
3        True
4        True
        ...
2325    False
2326    False
2327    False
2328    False
2329    False
Length: 2330, dtype: bool

In [128]:
df[df.isnull().any(axis=1)]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
3,24844,NaN,0.09,78.69,19.99,14,NaN,NaN,Small Business,Furniture,...,Central,NaN,NaN,55372.0,2015-05-12,2015-05-14,803.4705,16,1164.45,86838
4,24846,NaN,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372.0,2015-05-12,2015-05-13,-24.0300,7,22.23,86838
5,24847,Medium,0.05,3.28,4.20,14,Gwendolyn F Tyson,NaN,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372.0,2015-05-12,2015-05-13,-37.0300,4,13.99,86838
6,24848,Medium,0.05,3.58,1.63,14,NaN,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,NaN,2015-05-12,2015-05-13,-0.7100,4,14.26,86838
7,18181,NaN,0.00,4.42,4.99,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,East,New York,Smithtown,NaN,2015-04-08,2015-04-09,-59.8200,7,33.47,86837
8,20925,Medium,0.01,35.94,6.66,15,Timothy Reese,NaN,Small Business,Office Supplies,...,East,NaN,Smithtown,NaN,2015-05-28,2015-05-28,261.8757,10,379.53,86839
9,26267,NaN,0.04,2.98,1.58,16,Sarah Ramsey,NaN,Small Business,Office Supplies,...,East,NaN,Syracuse,13210.0,2015-02-12,2015-02-15,2.6300,6,18.80,86836
10,26268,High,0.05,115.99,2.50,16,Sarah Ramsey,NaN,Small Business,Technology,...,East,New York,NaN,13210.0,2015-02-12,2015-02-14,652.7331,10,945.99,86836
11,23890,High,0.05,26.48,6.93,18,Laurie Hanna,Regular Air,Small Business,Furniture,...,West,Montana,NaN,59601.0,2015-05-15,2015-05-16,314.4813,17,455.77,90031
12,24063,NaN,0.07,12.99,9.44,19,Jim Rodgers,NaN,Small Business,Technology,...,West,Montana,Missoula,NaN,2015-05-21,2015-05-23,-114.6399,18,231.79,90032
13,5890,High,0.05,26.48,6.93,21,Tony Wilkins Winters,Regular Air,Small Business,Furniture,...,East,New York,New York City,NaN,2015-05-15,2015-05-16,384.3800,70,1876.69,41793
14,6062,Not Specified,0.08,5.00,3.39,21,Tony Wilkins Winters,Regular Air,Small Business,Office Supplies,...,East,New York,NaN,10012.0,2015-05-21,2015-05-22,-17.4900,58,293.06,42949
16,20631,High,0.06,55.48,14.30,24,Edna Thomas,Regular Air,Corporate,Office Supplies,...,West,NaN,Laguna Niguel,NaN,2015-01-28,2015-01-29,-28.2968,1,67.49,87651
17,20632,High,0.02,1.68,1.57,24,Edna Thomas,Regular Air,Corporate,Office Supplies,...,West,NaN,Laguna Niguel,92677.0,2015-01-28,2015-01-30,-5.3072,1,2.25,87651
19,23509,High,0.08,34.99,7.73,32,Matthew Berman,Regular Air,Corporate,Office Supplies,...,West,Oregon,NaN,NaN,2015-02-22,2015-02-23,144.6900,13,424.68,89199
20,23612,High,0.01,17.98,8.51,32,Matthew Berman,Regular Air,Corporate,Technology,...,West,Oregon,NaN,NaN,2015-03-27,2015-03-28,-35.8788,2,40.17,89200
181,18261,Critical,0.06,276.20,24.49,335,Curtis O'Connell,Regular Air,Corporate,Furniture,...,West,Oregon,Medford,97504.0,2015-05-04,2015-05-05,2639.4708,14,3825.32,87277
271,18305,Critical,0.01,128.24,12.65,508,Cameron Owens,Regular Air,Corporate,Furniture,...,South,Kentucky,Covington,41011.0,2015-04-18,2015-04-21,140.1354,4,554.08,87357
483,24764,Critical,0.09,349.45,60.00,868,Sharon Ellis,Delivery Truck,Corporate,Furniture,...,Central,Minnesota,Shoreview,55126.0,2015-03-06,2015-03-07,-2946.0510,12,3918.98,91195
660,19185,High,0.09,349.45,60.00,1178,Sandy Hunt,Delivery Truck,Consumer,Furniture,...,South,Florida,Altamonte Springs,32701.0,2015-04-09,2015-04-10,-369.1100,7,2307.26,89787
700,20592,Medium,0.03,128.24,12.65,1237,Eva Simpson,Regular Air,Corporate,Furniture,...,Central,Texas,Carrollton,75007.0,2015-01-31,2015-02-02,790.4640,9,1145.60,86075
727,21848,Not Specified,0.08,128.24,12.65,1267,Rosemary Branch,Regular Air,Corporate,Furniture,...,South,Florida,Boca Raton,33433.0,2015-05-12,2015-05-13,-379.3440,3,366.44,89515
734,22125,Low,0.10,238.40,24.49,1281,Pauline Denton,Regular Air,Small Business,Furniture,...,Central,Indiana,Vincennes,47591.0,2015-01-24,2015-01-26,875.2844,8,1774.50,89112
736,4125,Low,0.10,238.40,24.49,1282,Dana Sharpe,Regular Air,Small Business,Furniture,...,East,Pennsylvania,Philadelphia,19134.0,2015-01-24,2015-01-26,460.6760,30,6654.39,29319
977,22593,High,0.09,349.45,60.00,1739,Edna Pierce,Delivery Truck,Corporate,Furniture,...,South,North Carolina,Goldsboro,27534.0,2015-05-03,2015-05-04,-90.7480,17,5835.41,85867
1228,19914,Not Specified,0.08,95.99,35.00,2211,Anita Hahn,Express Air,Home Office,Office Supplies,...,East,Maryland,Bowie,20715.0,2015-01-01,2015-01-03,-425.2084,2,193.88,88028
1507,19525,Critical,0.01,138.14,35.00,2660,Jeffrey Page,Regular Air,Small Business,Office Supplies,...,East,Maine,Gorham,4038.0,2015-02-24,2015-02-26,-321.5100,4,599.03,86486
1729,23188,High,0.06,276.20,24.49,3048,Tracy G Starr,Express Air,Corporate,Furniture,...,West,California,Berkeley,94704.0,2015-03-05,2015-03-07,1167.3800,10,2610.56,89789
1774,20795,Critical,0.08,349.45,60.00,3119,Jay Hubbard,Delivery Truck,Corporate,Furniture,...,South,Florida,Orlando,32839.0,2015-06-30,2015-07-02,513.0840,11,3772.19,86432
1860,18728,Not Specified,0.01,349.45,60.00,3257,Sharon Marcus,Delivery Truck,Consumer,Furniture,...,West,Washington,Longview,98632.0,2015-05-26,2015-05-27,3739.3929,15,5419.41,88825
1935,23182,Critical,0.09,276.20,24.49,3380,Eva Decker,Regular Air,Home Office,Furniture,...,South,Georgia,La Grange,30240.0,2015-04-20,2015-04-21,3193.2840,11,2941.42,88838
1943,19464,Not Specified,0.03,95.99,35.00,3388,Aaron Shaffer,Regular Air,Corporate,Office Supplies,...,West,California,Fairfield,94533.0,2015-05-11,2015-05-12,67.0120,9,894.64,90154
2045,18728,Not Specified,0.01,349.45,60.00,3257,Sharon Marcus,Delivery Truck,Consumer,Furniture,...,West,Washington,Longview,98632.0,2015-05-26,2015-05-27,3739.3929,15,5419.41,88825
2120,23182,Critical,0.09,276.20,24.49,3380,Eva Decker,Regular Air,Home Office,Furniture,...,South,Georgia,La Grange,30240.0,2015-04-20,2015-04-21,3193.2840,11,2941.42,88838
2128,19464,Not Specified,0.03,95.99,35.00,3388,Aaron Shaffer,Regular Air,Corporate,Office Supplies,...,West,California,Fairfield,94533.0,2015-05-11,2015-05-12,67.0120,9,894.64,90154
2230,18728,Not Specified,0.01,349.45,60.00,3257,Sharon Marcus,Delivery Truck,Consumer,Furniture,...,West,Washington,Longview,98632.0,2015-05-26,2015-05-27,3739.3929,15,5419.41,88825
2305,23182,Critical,0.09,276.20,24.49,3380,Eva Decker,Regular Air,Home Office,Furniture,...,South,Georgia,La Grange,30240.0,2015-04-20,2015-04-21,3193.2840,11,2941.42,88838
2313,19464,Not Specified,0.03,95.99,35.00,3388,Aaron Shaffer,Regular Air,Corporate,Office Supplies,...,West,California,Fairfield,94533.0,2015-05-11,2015-05-12,67.0120,9,894.64,90154

In [129]:
df_clean = df.drop_duplicates(keep=False)
df_clean

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221.0,2015-01-07,2015-01-08,4.56000,4,13.01,88522
1,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776.0,2015-06-13,2015-06-15,4390.36650,12,6362.85,90193
2,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203.0,2015-02-15,2015-02-17,-53.80960,22,211.15,90192
3,24844,NaN,0.09,78.69,19.99,14,NaN,NaN,Small Business,Furniture,...,Central,NaN,NaN,55372.0,2015-05-12,2015-05-14,803.47050,16,1164.45,86838
4,24846,NaN,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372.0,2015-05-12,2015-05-13,-24.03000,7,22.23,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1770,89,Critical,0.04,125.99,4.20,3106,Alexander O'Brien,Regular Air,Home Office,Technology,...,Central,Texas,Houston,77041.0,2015-03-20,2015-03-22,510.48900,47,4976.92,548
1771,21120,Not Specified,0.07,34.54,14.72,3113,Wayne English,Regular Air,Corporate,Office Supplies,...,South,Louisiana,New Iberia,70560.0,2015-05-17,2015-05-18,-20.18226,17,574.97,86860
1772,21121,Not Specified,0.02,12.28,6.47,3113,Wayne English,Regular Air,Corporate,Office Supplies,...,South,Louisiana,New Iberia,70560.0,2015-05-17,2015-05-17,-156.97220,9,115.22,86860
1773,21122,Not Specified,0.06,34.58,8.99,3113,Wayne English,Express Air,Corporate,Office Supplies,...,South,Louisiana,New Iberia,70560.0,2015-05-17,2015-05-19,384.50430,13,456.58,86860
1774,20795,Critical,0.08,349.45,60.00,3119,Jay Hubbard,Delivery Truck,Corporate,Furniture,...,South,Florida,Orlando,32839.0,2015-06-30,2015-07-02,513.08400,11,3772.19,86432

In [130]:
df_clean2=df.drop_duplicates(keep='first')
df_clean2

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221.0,2015-01-07,2015-01-08,4.5600,4,13.01,88522
1,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776.0,2015-06-13,2015-06-15,4390.3665,12,6362.85,90193
2,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203.0,2015-02-15,2015-02-17,-53.8096,22,211.15,90192
3,24844,NaN,0.09,78.69,19.99,14,NaN,NaN,Small Business,Furniture,...,Central,NaN,NaN,55372.0,2015-05-12,2015-05-14,803.4705,16,1164.45,86838
4,24846,NaN,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372.0,2015-05-12,2015-05-13,-24.0300,7,22.23,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1947,19842,High,0.01,10.90,7.46,3397,Andrea Shaw,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Danville,61832.0,2015-03-11,2015-03-12,-116.7600,18,207.31,87536
1948,19843,High,0.10,7.99,5.03,3397,Andrea Shaw,Regular Air,Small Business,Technology,...,Central,Illinois,Danville,61832.0,2015-03-11,2015-03-12,-160.9520,22,143.12,87536
1949,26208,Not Specified,0.08,11.97,5.81,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016.0,2015-03-29,2015-03-31,-41.8700,5,59.98,87534
1950,24911,Medium,0.10,9.38,4.93,3400,Florence Gold,Express Air,Small Business,Furniture,...,East,West Virginia,Fairmont,26554.0,2015-04-04,2015-04-04,-24.7104,15,135.78,87537
1951,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001.0,2015-02-08,2015-02-11,349.4850,5,506.50,87530

In [131]:
df_clean2=df.drop_duplicates(keep='last')
df_clean2

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221.0,2015-01-07,2015-01-08,4.5600,4,13.01,88522
1,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776.0,2015-06-13,2015-06-15,4390.3665,12,6362.85,90193
2,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203.0,2015-02-15,2015-02-17,-53.8096,22,211.15,90192
3,24844,NaN,0.09,78.69,19.99,14,NaN,NaN,Small Business,Furniture,...,Central,NaN,NaN,55372.0,2015-05-12,2015-05-14,803.4705,16,1164.45,86838
4,24846,NaN,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372.0,2015-05-12,2015-05-13,-24.0300,7,22.23,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2325,24014,Medium,0.04,300.98,54.92,107,Lois Hamilton,Delivery Truck,Consumer,Furniture,...,East,New Hampshire,Dover,3820.0,2015-04-06,2015-04-07,1684.4763,8,2441.27,88204
2326,18495,Medium,0.09,2.88,1.49,109,Tom McFarland,Regular Air,Consumer,Office Supplies,...,East,New Jersey,Lodi,7644.0,2015-06-22,2015-06-23,-2.7048,4,11.13,88205
2327,19074,High,0.03,4.26,1.20,114,Ron Newton,Regular Air,Home Office,Office Supplies,...,West,Oregon,Lake Oswego,97035.0,2015-01-03,2015-01-04,18.6580,7,29.50,89583
2328,19950,Medium,0.01,4.91,0.50,114,Ron Newton,Regular Air,Home Office,Office Supplies,...,West,Oregon,Lake Oswego,97035.0,2015-04-04,2015-04-06,40.2477,12,58.33,89584
2329,19951,Medium,0.09,4.00,1.30,114,Ron Newton,Express Air,Home Office,Office Supplies,...,West,Oregon,Lake Oswego,97035.0,2015-04-04,2015-04-06,14.0898,5,20.42,89584

In [132]:
df_clean2.shape

(1952, 25)

In [133]:
df_drop = df.dropna()
print(df.shape)   
print(df_drop.shape)

(2330, 25)
(2292, 25)

In [134]:
df = df.drop_duplicates(keep="first")
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1952 entries, 0 to 1951
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                1952 non-null   int64
 1   Order Priority        1947 non-null   object
 2   Discount              1952 non-null   float64
 3   Unit Price            1952 non-null   float64
 4   Shipping Cost         1952 non-null   float64
 5   Customer ID           1952 non-null   int64
 6   Customer Name         1950 non-null   object
 7   Ship Mode             1946 non-null   object
 8   Customer Segment      1952 non-null   object
 9   Product Category      1952 non-null   object
 10  Product Sub-Category  1952 non-null   object
 11  Product Container     1952 non-null   object
 12  Product Name          1952 non-null   object
 13  Product Base Margin   1936 non-null   float64
 14  Country               1952 non-null   object
 15  Region                1952 non-null   object
 16  State or Province     1947 non-null   object
 17  City                  1946 non-null   object
 18  Postal Code           1944 non-null   float64
 19  Order Date            1952 non-null   datetime64[ns]
 20  Ship Date             1952 non-null   datetime64[ns]
 21  Profit                1952 non-null   float64
 22  Quantity ordered new  1952 non-null   int64
 23  Sales                 1952 non-null   float64
 24  Order ID              1952 non-null   int64
dtypes: datetime64[ns](2), float64(7), int64(4), object(12)
memory usage: 396.5+ KB

In [135]:
duplicates_count = df.duplicated().sum()
print( duplicates_count)

0

In [136]:
df_clean = df.drop_duplicates()
df_clean

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221.0,2015-01-07,2015-01-08,4.5600,4,13.01,88522
1,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776.0,2015-06-13,2015-06-15,4390.3665,12,6362.85,90193
2,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203.0,2015-02-15,2015-02-17,-53.8096,22,211.15,90192
3,24844,NaN,0.09,78.69,19.99,14,NaN,NaN,Small Business,Furniture,...,Central,NaN,NaN,55372.0,2015-05-12,2015-05-14,803.4705,16,1164.45,86838
4,24846,NaN,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372.0,2015-05-12,2015-05-13,-24.0300,7,22.23,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1947,19842,High,0.01,10.90,7.46,3397,Andrea Shaw,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Danville,61832.0,2015-03-11,2015-03-12,-116.7600,18,207.31,87536
1948,19843,High,0.10,7.99,5.03,3397,Andrea Shaw,Regular Air,Small Business,Technology,...,Central,Illinois,Danville,61832.0,2015-03-11,2015-03-12,-160.9520,22,143.12,87536
1949,26208,Not Specified,0.08,11.97,5.81,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016.0,2015-03-29,2015-03-31,-41.8700,5,59.98,87534
1950,24911,Medium,0.10,9.38,4.93,3400,Florence Gold,Express Air,Small Business,Furniture,...,East,West Virginia,Fairmont,26554.0,2015-04-04,2015-04-04,-24.7104,15,135.78,87537
1951,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001.0,2015-02-08,2015-02-11,349.4850,5,506.50,87530

In [137]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1952 entries, 0 to 1951
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                1952 non-null   int64
 1   Order Priority        1947 non-null   object
 2   Discount              1952 non-null   float64
 3   Unit Price            1952 non-null   float64
 4   Shipping Cost         1952 non-null   float64
 5   Customer ID           1952 non-null   int64
 6   Customer Name         1950 non-null   object
 7   Ship Mode             1946 non-null   object
 8   Customer Segment      1952 non-null   object
 9   Product Category      1952 non-null   object
 10  Product Sub-Category  1952 non-null   object
 11  Product Container     1952 non-null   object
 12  Product Name          1952 non-null   object
 13  Product Base Margin   1936 non-null   float64
 14  Country               1952 non-null   object
 15  Region                1952 non-null   object
 16  State or Province     1947 non-null   object
 17  City                  1946 non-null   object
 18  Postal Code           1944 non-null   float64
 19  Order Date            1952 non-null   datetime64[ns]
 20  Ship Date             1952 non-null   datetime64[ns]
 21  Profit                1952 non-null   float64
 22  Quantity ordered new  1952 non-null   int64
 23  Sales                 1952 non-null   float64
 24  Order ID              1952 non-null   int64
dtypes: datetime64[ns](2), float64(7), int64(4), object(12)
memory usage: 396.5+ KB

In [138]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [139]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1952 entries, 0 to 1951
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                1952 non-null   int64
 1   Order Priority        1947 non-null   object
 2   Discount              1952 non-null   float64
 3   Unit Price            1952 non-null   float64
 4   Shipping Cost         1952 non-null   float64
 5   Customer ID           1952 non-null   int64
 6   Customer Name         1950 non-null   object
 7   Ship Mode             1946 non-null   object
 8   Customer Segment      1952 non-null   object
 9   Product Category      1952 non-null   object
 10  Product Sub-Category  1952 non-null   object
 11  Product Container     1952 non-null   object
 12  Product Name          1952 non-null   object
 13  Product Base Margin   1936 non-null   float64
 14  Country               1952 non-null   object
 15  Region                1952 non-null   object
 16  State or Province     1947 non-null   object
 17  City                  1946 non-null   object
 18  Postal Code           1944 non-null   float64
 19  Order Date            1952 non-null   datetime64[ns]
 20  Ship Date             1952 non-null   datetime64[ns]
 21  Profit                1952 non-null   float64
 22  Quantity ordered new  1952 non-null   int64
 23  Sales                 1952 non-null   float64
 24  Order ID              1952 non-null   int64
dtypes: datetime64[ns](2), float64(7), int64(4), object(12)
memory usage: 396.5+ KB

In [140]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1947    False
1948    False
1949    False
1950    False
1951    False
Length: 1952, dtype: bool

In [141]:
df

,row_id,order_priority,discount,unit_price,shipping_cost,customer_id,customer_name,ship_mode,customer_segment,product_category,...,region,state_or_province,city,postal_code,order_date,ship_date,profit,quantity_ordered_new,sales,order_id
0,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221.0,2015-01-07,2015-01-08,4.5600,4,13.01,88522
1,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776.0,2015-06-13,2015-06-15,4390.3665,12,6362.85,90193
2,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203.0,2015-02-15,2015-02-17,-53.8096,22,211.15,90192
3,24844,NaN,0.09,78.69,19.99,14,NaN,NaN,Small Business,Furniture,...,Central,NaN,NaN,55372.0,2015-05-12,2015-05-14,803.4705,16,1164.45,86838
4,24846,NaN,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372.0,2015-05-12,2015-05-13,-24.0300,7,22.23,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1947,19842,High,0.01,10.90,7.46,3397,Andrea Shaw,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Danville,61832.0,2015-03-11,2015-03-12,-116.7600,18,207.31,87536
1948,19843,High,0.10,7.99,5.03,3397,Andrea Shaw,Regular Air,Small Business,Technology,...,Central,Illinois,Danville,61832.0,2015-03-11,2015-03-12,-160.9520,22,143.12,87536
1949,26208,Not Specified,0.08,11.97,5.81,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016.0,2015-03-29,2015-03-31,-41.8700,5,59.98,87534
1950,24911,Medium,0.10,9.38,4.93,3400,Florence Gold,Express Air,Small Business,Furniture,...,East,West Virginia,Fairmont,26554.0,2015-04-04,2015-04-04,-24.7104,15,135.78,87537
1951,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001.0,2015-02-08,2015-02-11,349.4850,5,506.50,87530

In [142]:
df = df.drop_duplicates(keep="first")
df

,row_id,order_priority,discount,unit_price,shipping_cost,customer_id,customer_name,ship_mode,customer_segment,product_category,...,region,state_or_province,city,postal_code,order_date,ship_date,profit,quantity_ordered_new,sales,order_id
0,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221.0,2015-01-07,2015-01-08,4.5600,4,13.01,88522
1,20228,Not Specified,0.02,500.98,26.00,5,Ronnie Proctor,Delivery Truck,Home Office,Furniture,...,West,California,San Gabriel,91776.0,2015-06-13,2015-06-15,4390.3665,12,6362.85,90193
2,21776,Critical,0.06,9.48,7.29,11,Marcus Dunlap,Regular Air,Home Office,Furniture,...,East,New Jersey,Roselle,7203.0,2015-02-15,2015-02-17,-53.8096,22,211.15,90192
3,24844,NaN,0.09,78.69,19.99,14,NaN,NaN,Small Business,Furniture,...,Central,NaN,NaN,55372.0,2015-05-12,2015-05-14,803.4705,16,1164.45,86838
4,24846,NaN,0.08,3.28,2.31,14,Gwendolyn F Tyson,Regular Air,Small Business,Office Supplies,...,Central,Minnesota,Prior Lake,55372.0,2015-05-12,2015-05-13,-24.0300,7,22.23,86838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1947,19842,High,0.01,10.90,7.46,3397,Andrea Shaw,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Danville,61832.0,2015-03-11,2015-03-12,-116.7600,18,207.31,87536
1948,19843,High,0.10,7.99,5.03,3397,Andrea Shaw,Regular Air,Small Business,Technology,...,Central,Illinois,Danville,61832.0,2015-03-11,2015-03-12,-160.9520,22,143.12,87536
1949,26208,Not Specified,0.08,11.97,5.81,3399,Marvin Reid,Regular Air,Small Business,Office Supplies,...,Central,Illinois,Des Plaines,60016.0,2015-03-29,2015-03-31,-41.8700,5,59.98,87534
1950,24911,Medium,0.10,9.38,4.93,3400,Florence Gold,Express Air,Small Business,Furniture,...,East,West Virginia,Fairmont,26554.0,2015-04-04,2015-04-04,-24.7104,15,135.78,87537
1951,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001.0,2015-02-08,2015-02-11,349.4850,5,506.50,87530

In [143]:
df=df.fillna('unknown', inplace=True)
df

C:\Users\anwar salman\AppData\Local\Temp\ipykernel_13240\1739862580.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df=df.fillna('unknown', inplace=True)

In [149]:
import pandas as pd

df = pd.read_excel("C:/Users/anwar salman/OneDrive/Desktop/12/E-commerce project - Copy (4) - Copy.xlsx")

In [ ]:
region_summary = df.groupby("region")[["sales","profit"]].sum().reset_index()
print("=== Sales & Profit by Region ===")
print(region_summary)

=== Sales & Profit by Region ===
    region      sales        profit
0  Central  448284.70  77365.472669
1     East  592171.49  85291.403446
2    South  357105.12 -14424.054379
3     West  526776.57  75844.790102

In [ ]:
df["year"].value_counts()

year
2015    1952
Name: count, dtype: int64